Duration: ~20 minutes

# Hierarchical Forecasting in sktime

In many real-world forecasting problems we need to forecast **multiple related time series**.

These time series are often organized in a **hierarchy**.

For example:

Total Sales  
→ Category Sales  
→ Product Sales  

Hierarchical forecasting ensures that forecasts across these levels remain **consistent**.

In this tutorial we will:

- understand hierarchical time series structure
- train a simple forecasting model
- observe the **forecast inconsistency problem**
- apply **reconciliation methods** in sktime

## Hierarchical Data Structure

Hierarchical time series are stored using a **pandas MultiIndex**.

Each level of the index represents a level in the hierarchy.

Example structure:

Product line  
Product group  
Date

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

from tsbook.datasets.retail import SyntheticRetail

dataset = SyntheticRetail("hierarchical")

y_train, X_train, y_test, X_test = dataset.load(
    "y_train", "X_train", "y_test", "X_test"
)

## Inspecting the Dataset

In [2]:
y_train.head()

                            sales
group_id sku_id date
-1       20     2020-01-01      0
                2020-01-02      0
                2020-01-03      0
                2020-01-04      0
                2020-01-05      2

We can count how many individual time series exist in the hierarchy.

In [3]:
y_train.index.droplevel(-1).nunique()

31

Some identifiers represent aggregated levels.

For example the identifier `("__total", "__total")` represents the total across all products.

In [4]:
y_train.loc[("__total", "__total")].head()

            sales
date
2020-01-01     24
2020-01-02     19
2020-01-03     14
2020-01-04     23
2020-01-05     23

## Conceptual Hierarchy

A simple hierarchy may look like this:

<pre>
Total
├── Food preparation
│   ├── Hobs
│   └── Ovens
└── Food preservation
    ├── Fridges
    └── Freezers
</pre>

## Forecasting Without Reconciliation

We now train a simple forecasting model.

To keep the example fast and easy to run we use a **NaiveForecaster**.

In [5]:
from sktime.forecasting.naive import NaiveForecaster

forecaster = NaiveForecaster(strategy="last")

forecaster.fit(y_train)

NaiveForecaster()

We now generate forecasts for the test horizon.

In [6]:
fh = y_test.index.get_level_values(-1).unique()

y_pred = forecaster.predict(fh)

## Forecast Inconsistency

When we forecast each series independently, hierarchical relationships may be violated.

For example:

Sum(child forecasts) ≠ Parent forecast

In [7]:
from sktime.transformations.hierarchical.aggregate import Aggregator
import warnings
warnings.filterwarnings('ignore')

Aggregator().fit_transform(y_pred) - y_pred

                             sales
group_id sku_id  date
-1       20      2024-07-06    0.0
                 2024-07-07    0.0
                 2024-07-08    0.0
                 2024-07-09    0.0
                 2024-07-10    0.0
...                            ...
__total  __total 2024-12-28    0.0
                 2024-12-29    0.0
                 2024-12-30    0.0
                 2024-12-31    0.0
                 2025-01-01    0.0

[5580 rows x 1 columns]

The differences above show that the forecasts are **not consistent** across the hierarchy.

To fix this we use **reconciliation methods**.

## Bottom-Up Reconciliation

The bottom-up strategy forecasts the **lowest level series** and aggregates them to higher levels.

In [8]:
from sktime.transformations.hierarchical.reconcile import BottomUpReconciler

bottom_up = BottomUpReconciler() * forecaster

bottom_up.fit(y_train)

y_pred_bottomup = bottom_up.predict(fh=fh)

In [9]:
Aggregator().fit_transform(y_pred_bottomup) - y_pred_bottomup

                             sales
group_id sku_id  date
-1       20      2024-07-06    0.0
                 2024-07-07    0.0
                 2024-07-08    0.0
                 2024-07-09    0.0
                 2024-07-10    0.0
...                            ...
__total  __total 2024-12-28    0.0
                 2024-12-29    0.0
                 2024-12-30    0.0
                 2024-12-31    0.0
                 2025-01-01    0.0

[5580 rows x 1 columns]

Now the forecasts are consistent across the hierarchy.

## Top-Down Reconciliation

Top-down forecasting starts from the **total series** and distributes forecasts to lower levels.

In [10]:
from sktime.transformations.hierarchical.reconcile import TopdownReconciler

top_down = TopdownReconciler() * forecaster

top_down.fit(y_train)

y_pred_topdown = top_down.predict(fh=fh)

## Optimal Reconciliation

In [11]:
from sktime.forecasting.reconcile import ReconcilerForecaster

# This wraps the forecaster and reconciliation method into one object
optimal = ReconcilerForecaster(forecaster=forecaster, method="ols")

optimal.fit(y_train)
y_pred_optimal = optimal.predict(fh=fh)

## MinT Reconciliation

In [12]:
from sktime.forecasting.reconcile import ReconcilerForecaster

mint = ReconcilerForecaster(
    forecaster=forecaster,
    method="mint_shrink"
)

mint.fit(y_train)

y_pred_mint = mint.predict(fh=fh)

## Comparing Reconciliation Methods

In [13]:
from sktime.performance_metrics.forecasting import MeanSquaredScaledError

metric = MeanSquaredScaledError(multilevel="uniform_average_time")

pd.DataFrame(
    {
        "Baseline": metric(y_test, y_pred, y_train=y_train),
        "BottomUp": metric(y_test, y_pred_bottomup, y_train=y_train),
        "TopDown": metric(y_test, y_pred_topdown, y_train=y_train),
        "OLS": metric(y_test, y_pred_optimal, y_train=y_train),
        "MinT": metric(y_test, y_pred_mint, y_train=y_train),
    },
    index=["MSSE"],
)

       Baseline   BottomUp    TopDown        OLS       MinT
MSSE  39.657047  39.657047  39.657047  39.657047  39.657047

## Key Takeaways

Hierarchical forecasting deals with multiple related time series organized in levels.

Independent forecasts can lead to **inconsistent predictions** across the hierarchy.

Reconciliation methods adjust forecasts to enforce hierarchical constraints.

sktime provides several reconciliation strategies including:

- Bottom-Up
- Top-Down
- Optimal Reconciliation
- MinT

These tools allow practitioners to build forecasting systems that respect hierarchical structure.