# Hierarchical, Panel and Global Forecasting with `sktime`

### Overview of this notebook

* introduction - hierarchical time series
* hierarchical and panel data format in sktime
* automated vectorization of forecasters and transformers
* hierarchical reconciliation in sktime
* hierarchical forecasting/Global forecasting using summarization/reduction models, "M5 winner"
* extender guide
* introduction - global forecasting
* global forecast without exogeneous data
* global forecast with exogeneous data
* contributor credits

In [1]:
%%capture
import warnings

warnings.filterwarnings("ignore")

---
## Hierarchical time series

Time series are often present in "hierarchical" form, example:

<img src="./img/hierarchytree.png" width="1200" alt="arrow heads">

Examples include:
* Product sales in different categories (e.g. M5 time series competition)
* Tourism demand in different regions
* Balance sheet structures across cost centers / accounts

Many hierarchical time series datasets can be found here:
https://forecastingdata.org/
(access loader in development)

For literature see also:
https://otexts.com/fpp2/hierarchical.html

A time series can also exhibit multiple independent hierarchies:

<img src="./img/hierarchytree_grouped.png" width="1200" alt="arrow heads">

---

### Representation of hierarchical and panel datatypes

`sktime` distinguishes as abstract scientific data types for time series (="scitypes"):

* `Series` type = one time series (uni or multivariate)
* `Panel` type = collection of multiple time series, flat hierarchy
* `Hierarchical` type = hierarchical collection of time series, as above

Each scitype has multiple mtype representations.

For simplicity, we focus only on `pandas.DataFrame` based representations below.

In [2]:
# import to retrieve examples

from sktime.datatypes import get_examples

#### Individual time series - `Series` scitype, `"pd.DataFrame"` mtype

In the `"pd.DataFrame"` mtype, time series are represented by an in-memory container `obj: pandas.DataFrame` as follows.

* structure convention: `obj.index` must be monotonic, and one of `Int64Index`, `RangeIndex`, `DatetimeIndex`, `PeriodIndex`.
* variables: columns of `obj` correspond to different variables
* variable names: column names `obj.columns`
* time points: rows of `obj` correspond to different, distinct time points
* time index: `obj.index` is interpreted as a time index.
* capabilities: can represent multivariate series; can represent unequally spaced series

Example of a univariate series in `"pd.DataFrame"` representation.\
This series has two variables, named `"a"` and `"b"`. Both are observed at the same four time points 0, 1, 2, 3.

In [3]:
get_examples(mtype="pd.DataFrame")[0]

     a
0  1.0
1  4.0
2  0.5
3 -3.0

Example of a bivariate series in `"pd.DataFrame"` representation.\
This series has two variables, named `"a"` and `"b"`. Both are observed at the same four time points 0, 1, 2, 3.

In [4]:
get_examples(mtype="pd.DataFrame")[1]

     a         b
0  1.0  3.000000
1  4.0  7.000000
2  0.5  2.000000
3 -3.0 -0.428571

#### Panels (= flat collections) of time series - `Panel` scitype, `"pd-multiindex"` mtype

In the `"pd-multiindex"` mtype, time series panels are represented by an in-memory container `obj: pandas.DataFrame` as follows.

* structure convention: `obj.index` must be a pair multi-index of type `(RangeIndex, t)`, where `t` is one of `Int64Index`, `RangeIndex`, `DatetimeIndex`, `PeriodIndex` and monotonic.
* instances: rows with the same `"instances"` index correspond to the same instance; rows with different `"instances"` index correspond to different instances.
* instance index: the first element of pairs in `obj.index` is interpreted as an instance index. 
* variables: columns of `obj` correspond to different variables
* variable names: column names `obj.columns`
* time points: rows of `obj` with the same `"timepoints"` index correspond to the same time point; rows of `obj` with different `"timepoints"` index correspond to the different time points.
* time index: the second element of pairs in `obj.index` is interpreted as a time index. 
* capabilities: can represent panels of multivariate series; can represent unequally spaced series; can represent panels of unequally supported series; cannot represent panels of series with different sets of variables.

Example of a panel of multivariate series in `"pd-multiindex"` mtype representation.
The panel contains three multivariate series, with instance indices 0, 1, 2. All series have two variables with names `"var_0"`, `"var_1"`. All series are observed at three time points 0, 1, 2.

In [5]:
get_examples(mtype="pd-multiindex")[0]

                      var_0  var_1
instances timepoints
0         0               1      4
          1               2      5
          2               3      6
1         0               1      4
          1               2     55
          2               3      6
2         0               1     42
          1               2      5
          2               3      6

#### Hierarchical time series - `Hierarchical` scitype, `"pd_multiindex_hier"` mtype

* structure convention: `obj.index` must be a 3 or more level multi-index of type `(RangeIndex, ..., RangeIndex, t)`, where `t` is one of `Int64Index`, `RangeIndex`, `DatetimeIndex`, `PeriodIndex` and monotonic. We call the last index the "time-like" index
* hierarchy level: rows with the same non-time-like indices correspond to the same hierarchy unit; rows with different non-time-like index combination correspond to different hierarchy unit.
* hierarchy: the non-time-like indices in `obj.index` are interpreted as a hierarchy identifying index. 
* variables: columns of `obj` correspond to different variables
* variable names: column names `obj.columns`
* time points: rows of `obj` with the same `"timepoints"` index correspond to the same time point; rows of `obj` with different `"timepoints"` index correspond to the different time points.
* time index: the last element of tuples in `obj.index` is interpreted as a time index. 
* capabilities: can represent hierarchical series; can represent unequally spaced series; can represent unequally supported hierarchical series; cannot represent hierarchical series with different sets of variables.

In [6]:
X = get_examples(mtype="pd_multiindex_hier")[0]
X

                    var_0  var_1
foo bar timepoints
a   0   0               1      4
        1               2      5
        2               3      6
    1   0               1      4
        1               2     55
        2               3      6
    2   0               1     42
        1               2      5
        2               3      6
b   0   0               1      4
        1               2      5
        2               3      6
    1   0               1      4
        1               2     55
        2               3      6
    2   0               1     42
        1               2      5
        2               3      6

In [7]:
X.index.get_level_values(level=-1)

Index([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2], dtype='int64', name='timepoints')

---

### Automated vectorization (casting) of forecasters and transformers

Many transformers and forecasters implemented for single series

`sktime` automatically vectorizes/"up-casts" them to hierarchical data

"apply by individual series/panel in the hierarchical structure"

constructing a hierarchical time series:

In [8]:
from sktime.utils._testing.hierarchical import _make_hierarchical

y = _make_hierarchical()
y

                            c0
h0   h1   time
h0_0 h1_0 2000-01-01  4.890965
          2000-01-02  4.162906
          2000-01-03  2.396068
          2000-01-04  3.617121
          2000-01-05  3.704492
...                        ...
h0_1 h1_3 2000-01-08  2.363052
          2000-01-09  5.628371
          2000-01-10  1.590486
          2000-01-11  2.495301
          2000-01-12  2.795948

[96 rows x 1 columns]

all forecasters and transformers are applicable to this!\
if forecaster implements logic for single series only, "apply to all hierarchy units"

In [9]:
from sktime.forecasting.arima import ARIMA

forecaster = ARIMA()

y_pred = forecaster.fit(y, fh=[1, 2]).predict()
y_pred

                            c0
h0   h1   time
h0_0 h1_0 2000-01-13  4.011083
          2000-01-14  3.938423
     h1_1 2000-01-13  4.162070
          2000-01-14  3.837325
     h1_2 2000-01-13  3.569800
          2000-01-14  3.585248
     h1_3 2000-01-13  3.312264
          2000-01-14  3.392929
h0_1 h1_0 2000-01-13  3.955279
          2000-01-14  3.975636
     h1_1 2000-01-13  4.167355
          2000-01-14  3.500118
     h1_2 2000-01-13  3.760504
          2000-01-14  3.763340
     h1_3 2000-01-13  3.755343
          2000-01-14  3.586705

individual forecasters fitted per hierarchy level are stored in the  `forecasters_` attribute\
this contains a `pandas.DataFrame` in the same format as the hierarchy levels, and fitted forecasters inside\
(for transformers, the attribute is called `transformers_`)

In [10]:
forecaster.forecasters_

          forecasters
h0_0 h1_0     ARIMA()
     h1_1     ARIMA()
     h1_2     ARIMA()
     h1_3     ARIMA()
h0_1 h1_0     ARIMA()
     h1_1     ARIMA()
     h1_2     ARIMA()
     h1_3     ARIMA()

to access or inspect individual forecasters, access elements of the `forecasters_` data frame:

In [11]:
forecaster.forecasters_.iloc[0, 0].summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                   12
Model:               SARIMAX(1, 0, 0)   Log Likelihood                 -14.307
Date:                Sun, 16 Feb 2025   AIC                             34.614
Time:                        17:32:07   BIC                             36.068
Sample:                             0   HQIC                            34.075
                                 - 12
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept      2.0438      1.492      1.369      0.171      -0.881       4.969
ar.L1          0.4724      0.385      1.228      0.220      -0.282       1.226
sigma2         0.6222      0.348      1.786      0.074      -0.060       1.305
===================================================================================
Ljung-Box (L1) (Q):                   0.37   Jarque-Bera (JB):                 0.90
Prob(Q):                              0.54   Prob(JB):                         0.64
Heteroskedasticity (H):               0.41   Skew:                            -0.57
Prob(H) (two-sided):                  0.40   Kurtosis:                         2.30
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

auto-vectorization is also performed for probabilistic forecasts (see notebook 2):

In [12]:
forecaster.predict_interval()

                            c0
                           0.9
                         lower     upper
h0   h1   time
h0_0 h1_0 2000-01-13  2.713605  5.308561
          2000-01-14  2.503483  5.373363
     h1_1 2000-01-13  2.325116  5.999025
          2000-01-14  1.967973  5.706677
     h1_2 2000-01-13  2.265449  4.874152
          2000-01-14  2.183641  4.986854
     h1_3 2000-01-13  1.561885  5.062643
          2000-01-14  1.615546  5.170311
h0_1 h1_0 2000-01-13  2.435657  5.474901
          2000-01-14  2.408696  5.542577
     h1_1 2000-01-13  3.170080  5.164631
          2000-01-14  2.443799  4.556436
     h1_2 2000-01-13  2.574963  4.946045
          2000-01-14  2.577726  4.948955
     h1_3 2000-01-13  1.766964  5.743722
          2000-01-14  1.567843  5.605568

which level a forecaster/natively implements and when vectorization occurs is determined by the "inner mtype" attributes.

For forecasters, inspect `y_inner_mtype`, this is a list of internally supported machine types:

In [13]:
forecaster.get_tag("y_inner_mtype")

'pd.Series'

ARIMA supports only one `Series` level mtype.
For a register of all mtype codes and their corresponding scitype (series, panel or hierarchical),\
see `sktime.datatypes.MTYPE_REGISTER` (convert to `pandas.DataFrame` for pretty-printing)

In [14]:
import pandas as pd

from sktime.datatypes import MTYPE_REGISTER

pd.DataFrame(MTYPE_REGISTER)

,0,1,2
0,pd.Series,Series,pd.Series representation of a univariate series
1,pd.DataFrame,Series,pd.DataFrame representation of a uni- or multi...
2,np.ndarray,Series,"2D numpy.ndarray with rows=samples, cols=varia..."
3,xr.DataArray,Series,xr.DataArray representation of a uni- or multi...
4,dask_series,Series,xdas representation of a uni- or multivariate ...
5,pl.DataFrame,Series,pl.DataFrame representation of a uni- or multi...
6,gluonts_ListDataset_series,Series,gluonTS representation of univariate and multi...
7,nested_univ,Panel,"pd.DataFrame with one column per variable, pd...."
8,numpy3D,Panel,"3D np.array of format (n_instances, n_columns,..."
9,numpyflat,Panel,"WARNING: only for internal use, not a fully su..."
10,pd-multiindex,Panel,"pd.DataFrame with multi-index (instances, time..."
11,pd-wide,Panel,"pd.DataFrame in wide format, cols = (instance*..."
12,pd-long,Panel,"pd.DataFrame in long format, cols = (index, ti..."
13,df-list,Panel,list of pd.DataFrame
14,gluonts_ListDataset_panel,Panel,gluonTS representation of univariate and multi...
15,gluonts_PandasDataset_panel,Panel,gluonTS representation of a pandas DataFrame
16,polars_panel,Panel,"Polars frame representing a Panel, with one in..."
17,pd_multiindex_hier,Hierarchical,pd.DataFrame with MultiIndex
18,dask_hierarchical,Hierarchical,"dask frame with multiple hierarchical indices,..."
19,polars_hierarchical,Hierarchical,polars frame with multiple hierarchical indice...
20,alignment,Alignment,"pd.DataFrame in alignment format, values are i..."
21,alignment_loc,Alignment,"pd.DataFrame in alignment format, values are l..."
22,pd_DataFrame_Table,Table,pd.DataFrame representation of a data table
23,numpy1D,Table,1D np.narray representation of a univariate da...
24,numpy2D,Table,2D np.narray representation of a multivariate ...
25,pd_Series_Table,Table,pd.Series representation of a univariate data ...
26,list_of_dict,Table,list of dictionaries with primitive entries
27,polars_eager_table,Table,polars.DataFrame representation of a data table
28,polars_lazy_table,Table,polars.LazyFrame representation of a data table
29,pred_interval,Proba,predictive intervals
30,pred_quantiles,Proba,quantile predictions
31,pred_var,Proba,variance predictions

roadmap items:

* interfacing and implementing common methods with native hierarchical support
    * ARIMA using hierarchy factors, GEE, mixed effects
* wrappers for "using hierarchy levels" as covariates or exogeneous features
* full vectorization over variables to render univariate forecasters multivariate

contributions are appreciated!

---

### Hierarchical reconciliation

#### Why do we need hierarchical reconciliation

forecast reconciliation = ensuring that linear hierarchy dependencies are met,\
e.g., "sum of individual shop sales in Berlin must equal sum of total sales in Berlin"\
requires hierarchical (or panel) data, usually involves totals. 

**Bottom-up reconciliation** works by generating forecasts only at the lowest level and then aggregating them to obtain totals at higher levels.

- Arguably the simplest algorithm for reconciling forecasts across hierarchies.
- **Advantages**: Easy to implement and captures the peculiarities of lower levels in the hierarchy.
- **Disadvantages**: Lower levels tend to exhibit excess volatility, which gets aggregated upward, often leading to less accurate top-level forecasts.

**Top-down reconciliation** works by first generating top-level forecasts and then distributing them across lower levels based on predefined proportions. There are two primary approaches:

- **Forecast proportions (`td_fcst`)**: Keep the total forecast unchanged, forecast the non-total levels separately, and then transform these forecasts into proportions of the total. Finally, multiply these proportions by the total forecast to obtain forecasts for all levels.
  - **Advantages**: If the top level is easy to forecast, this method can improve overall accuracy. Standard forecasting models can be applied at non-total levels since they remain in the original domain.
  - **Disadvantages**: Heavily dependent on the accuracy of the top-level forecast.

- **Historical proportions (`td_share`)**: Forecast the top level, convert non-total series into shares relative to their parent, and then multiply these shares by the top-level forecast.
  - **Advantages**: Easy to implement, stable at the top level, and shares may be easier to forecast than the original series.
  - **Disadvantages**: Susceptible to errors in both the top-level forecast and the stability of the historical shares.

**Optimal forecast reconciliation** generates forecasts at all levels and adjusts them in a way that minimizes forecast errors.

- **Advantages**: If the error covariance matrix is correctly specified, this method can yield the most accurate forecasts.
- **Disadvantages**: When dealing with a large number of time series, estimating the covariance matrix can be challenging.

The optimal forecast, in the original implementation, may not respect non-negative constraints. Fortunately, sktime includes an implementation of the optimal forecast reconciliation algorithm that respects these constraints.

`sktime` provides functionality for reconciliation:

* data container convention for node-wise aggregates
* functionality to compute node-wise aggregates - `Aggregator`
    * can be used for bottom-up reconciliation
* transformer implementing reconciliation logic - `BottomUpReconciler()`, `TopdownReconciler("td_fcst")`, `TopdownReconciler("td_share")`, `OptimalReconciler("ols")`
    * these transformations are meant to be used in a pipeline, by preprocessing the data before fitting a forecaster and postprocessing the forecasts
* `Reconcile` - the previous version of reconciliation in sktime, that is meant to reconcile forecasts, without a pipeline, when possible.

#### The node-wise aggregate data format

`sktime` uses a special case of the `pd_multiindex_hier` format to store node-wise aggregates:

* a `__total` index element in an instance (non-time-like) level indicates summation over all instances below that level
* the `__total` index element is reserved and cannot be used for anything else
* entries below a `__total` index element are sums of entries over all other instances in the same levels where a `__total` element is found

#### The aggregation transformer

The node-wise aggregated format can be obtained by applying the `Aggregator` transformer.

In a pipeline with non-aggregate dinput, this allows making forecasts by totals.

In [15]:
from sktime.datatypes import get_examples

y_hier = get_examples("pd_multiindex_hier")[1]
y_hier

                    var_0
foo bar timepoints
a   0   0               1
        1               2
        2               3
    1   0               1
        1               2
        2               3
    2   0               1
        1               2
        2               3
b   0   0               1
        1               2
        2               3
    1   0               1
        1               2
        2               3
    2   0               1
        1               2
        2               3

In [16]:
from sktime.transformations.hierarchical.aggregate import Aggregator

Aggregator().fit_transform(y_hier)

                            var_0
foo     bar     timepoints
__total __total 0               6
                1              12
                2              18
a       0       0               1
                1               2
                2               3
        1       0               1
                1               2
                2               3
        2       0               1
                1               2
                2               3
        __total 0               3
                1               6
                2               9
b       0       0               1
                1               2
                2               3
        1       0               1
                1               2
                2               3
        2       0               1
                1               2
                2               3
        __total 0               3
                1               6
                2               9

If used at the start of a pipeline, forecasts are made for node `__total`-s as well as individual instances.

Note: in general, this does not result in a reconciled forecast, i.e., forecast totals will not add up.

In [17]:
from sktime.forecasting.naive import NaiveForecaster

pipeline_to_forecast_totals = Aggregator() * NaiveForecaster()

pipeline_to_forecast_totals.fit(y_hier, fh=[1, 2])
pipeline_to_forecast_totals.predict()

                    var_0
foo bar timepoints
a   0   3             3.0
        4             3.0
    1   3             3.0
        4             3.0
    2   3             3.0
        4             3.0
b   0   3             3.0
        4             3.0
    1   3             3.0
        4             3.0
    2   3             3.0
        4             3.0

#### Reconciling with transformations

To make forecasts add up, we can use a reconciliation method, such as `BottomUpReconciler`, `TopdownReconciler`, `MiddleOutReconciler`, `OptimalReconciler` or `NonNegativeOptimalReconciler`.

In [28]:
from sktime.forecasting.naive import NaiveForecaster
from sktime.transformations.hierarchical.reconcile import (
    TopdownReconciler,
)

pipeline_to_forecast_totals = TopdownReconciler() * NaiveForecaster()
pipeline_to_forecast_totals

TransformedTargetForecaster(steps=[TopdownReconciler(), NaiveForecaster()])

In [29]:
pipeline_to_forecast_totals.fit(y_hier, fh=[1, 2])
pipeline_to_forecast_totals.predict()

                    var_0
foo bar timepoints
a   0   3             3.0
        4             3.0
    1   3             3.0
        4             3.0
    2   3             3.0
        4             3.0
b   0   3             3.0
        4             3.0
    1   3             3.0
        4             3.0
    2   3             3.0
        4             3.0

Internally, the pipeline calls `reconciler.transform` to preprocess and filter the relevant data to be forecasted.
At the end of the pipeline, the reconciler is called with `inverse_transform` to reconcile the forecasts. We can also do it step-by-step, without a pipeline.

In [30]:
reconciler = TopdownReconciler()
y_hier_transformed = reconciler.fit_transform(y_hier)
y_hier_transformed

                            var_0
foo     bar     timepoints
__total __total 0               6
                1              12
                2              18
a       0       0               1
                1               2
                2               3
        1       0               1
                1               2
                2               3
        2       0               1
                1               2
                2               3
        __total 0               3
                1               6
                2               9
b       0       0               1
                1               2
                2               3
        1       0               1
                1               2
                2               3
        2       0               1
                1               2
                2               3
        __total 0               3
                1               6
                2               9

We add some noise to showcase how it adjusts the forecasts. The inverse transform
keeps only timeseries that were present in the original data.

In [26]:
import numpy as np

y_hier_transformed_noise = y_hier_transformed + np.random.normal(
    0, 1, y_hier_transformed.shape
)

y_hier_reconc = reconciler.inverse_transform(y_hier_transformed_noise)
y_hier_reconc

                       var_0
foo bar timepoints
a   0   0           2.706654
        1           1.374370
        2           4.729145
    1   0          -0.256933
        1           3.035066
        2           1.852927
    2   0           0.527993
        1           1.724674
        2           2.218673
b   0   0           4.068838
        1           0.886660
        2           2.084540
    1   0          -3.092240
        1           3.127753
        2           3.474135
    2   0           1.991414
        1           2.873285
        2           2.947641

#### Using ReconcilerForecaster

The `ReconcilerForecaster` wraps all reconciliation methods together with a forecaster, and, in the case of optimal reconciliation, computes the error covariance matrix. The `mint_shrink` is a optimal reconciliation method that shrinks the error covariance matrix to improve the estimate.

In [31]:
from sktime.forecasting.reconcile import ReconcilerForecaster

forecaster = ReconcilerForecaster(forecaster=NaiveForecaster(), method="mint_shrink")
forecaster.fit(y_hier)
forecaster.predict(fh=[1, 2])

                            var_0
foo     bar     timepoints
__total __total 3            18.0
                4            18.0
a       0       3             3.0
                4             3.0
        1       3             3.0
                4             3.0
        2       3             3.0
                4             3.0
        __total 3             9.0
                4             9.0
b       0       3             3.0
                4             3.0
        1       3             3.0
                4             3.0
        2       3             3.0
                4             3.0
        __total 3             9.0
                4             9.0

Roadmap items:

* reconciliation of wrapper type
* reconciliation & Global forecasting
* probabilistic reconciliation

---

## Global forecasting in `sktime`

### Global forecasting/Panel forecasting - introduction

Global forecasting = training **across sets of time series**, i.e., on time series **panels**.\
Typically better than "fit one forecaster per time series instance".

Also called:

* "panel forecasting", if forecasting all time series
* "cross-learning", if training time series are disjoint from deployment set

 Why does Global forecasting matter?

 * In practice, we often have time series of limited range
 * Estimation is difficult, and we cannot model complex dependencies
 * Assumption of Global forecasting: We can observe the identical data generating process (DGP) multiple times
 * Non-identical DGPs can be fine too, as long as the degree of dissimilarity is captured by exogeneous information
 * Now we have much more information and can estimate more reliably and more complex models (caveat: unless complexity is purely driven by time dynamics)
 
As a result of these advantages, Global forecasting models have been very successful in competition, e.g.
* Rossmann Store Sales
* Walmart Sales in Stormy Weather
* M5 competition

Many business problems in practice are essentially Global forecasting problem - often also reflecting hierarchical information (see above)
* Product sales in different categories (e.g. M5 time series competition)
* Balance sheet structures across cost centers / accounts
* Dynamics of pandemics observed at different points in time

Distinction to multivariate forecasting
* Multivariate forecasting focuses on modeling interdependence between time series
* Global forecasting can model interdependence, but focus lies on enhancing observation space

Implementation in sktime

* All models support panel forecasts - these may be independent or dependent
    * some models' panel forecasts use all time series, e.g., reduction forecasters
* Models that can train on disjoint examples ("cross-learning") have the `capability:global_forecasting` tag

### Panel forecasting with reduction forecasters

For the following example we will use the `"pd-multiindex"` representation of the `"Panel"` scitype (see above)

Row multiindex level 0 is the unique identifier for the individual time series, level 1 contains the time index.

In [21]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline

from sktime.forecasting.compose import make_reduction
from sktime.split import temporal_train_test_split
from sktime.transformations.date import DateTimeFeatures

pd.options.mode.chained_assignment = None
pd.set_option("display.max_columns", None)

# %%
# Load M5 Data and prepare
y = pd.read_pickle("global_fc/y.pkl")
X = pd.read_pickle("global_fc/X.pkl")

`y`/`X` are based on the M5 competition.
The data features sales of products in different stores, different states and different product categories. 

For a detailed analysis of the competition please take a look at the paper 
"M5 accuracy competition: Results, findings, and conclusions".

https://doi.org/10.1016/j.ijforecast.2021.11.013

You can see 
a glimpse of the data here:

In [22]:
print(y.head())
print(X.head())

                            y
instances timepoints
1         2016-03-15   756.67
          2016-03-16   679.13
          2016-03-17   633.40
          2016-03-18  1158.04
          2016-03-19   914.24
                      dept_id  cat_id  store_id  state_id  event_name_1  \
instances timepoints
1         2016-03-15        1       1        10         3             1
          2016-03-16        1       1        10         3             1
          2016-03-17        1       1        10         3             7
          2016-03-18        1       1        10         3             1
          2016-03-19        1       1        10         3             1

                      event_type_1  event_name_2  event_type_2  snap  \
instances timepoints
1         2016-03-15             1             1             1     3
          2016-03-16             1             1             1     0
          2016-03-17             3             1             1     0
          2016-03-18             1             1             1     0
          2016-03-19             1             1             1     0

                      no_stock_days
instances timepoints
1         2016-03-15              0
          2016-03-16              0
          2016-03-17              0
          2016-03-18              0
          2016-03-19              0


* time series grouped via the instances argument in the first column = Panel
* focus on modeling individual products
* hierarchical information is provided as exgoneous information. 

For the M5 competition, winning solution used exogeneous features about the hierarchies like `"dept_id"`, `"store_id"` etc. to capture similarities and dissimilarities of the products. Other features include holiday events and snap days (specific assistance program of US social security paid on certain days).

now split into test and train set using `temporal_train_test_split`.\
we can cut every instance of the time series individually:

In [23]:
y_train, y_test, X_train, X_test = temporal_train_test_split(y, X)
print(y_train.head(5))
print(y_test.head(5))

                            y
instances timepoints
1         2016-03-15   756.67
          2016-03-16   679.13
          2016-03-17   633.40
          2016-03-18  1158.04
          2016-03-19   914.24

                            y
instances timepoints
1         2016-04-14   874.57
          2016-04-15   895.29
          2016-04-16  1112.63
          2016-04-17  1014.86
          2016-04-18   691.91

both `y` and `X` are split in the same way, and hierarchy structures are preserved.

#### Rationale for tree based models

Tree ensembles exploit complex non-linear relationships / dependencies between time series and covariates.

In **univariate time series forecasting**, tree based models often do not perform well due to lack of data.

Due to large effective sample sizes in **Global forecasting** , tree ensembles can become a good choice (e.g., 42,840 time series in the M5 competition).

sktime can interface any sklearn compatible model via reduction, e.g., `RandomForestRegressor`.

In [24]:
regressor = make_pipeline(
    RandomForestRegressor(random_state=1),
)

Caveat: reduction applies a supervised regressor to a time series, i.e., to a task for which they were not originally designed.

This issue can be addressed by generating features that capture the dynamics of the time series.\
`"WindowSummarizer"` can be used to generate features useful for time series forecasting,\
 based on a provided dictionary of functions, window shifts and window lengths:

In [25]:
import pandas as pd

from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.compose import ForecastingPipeline
from sktime.transformations.summarize import WindowSummarizer

kwargs = {
    "lag_feature": {
        "lag": [1],
        "mean": [[1, 3], [3, 6]],
        "std": [[1, 4]],
    }
}

transformer = WindowSummarizer(**kwargs)
y_transformed = transformer.fit_transform(y_train)

y_transformed.head(10)

                      y_lag_1   y_mean_1_3  y_mean_3_6   y_std_1_4
instances timepoints
1         2016-03-15      NaN          NaN         NaN         NaN
          2016-03-16   756.67          NaN         NaN         NaN
          2016-03-17   679.13          NaN         NaN         NaN
          2016-03-18   633.40   689.733333         NaN         NaN
          2016-03-19  1158.04   823.523333         NaN  239.617572
          2016-03-20   914.24   901.893333         NaN  241.571143
          2016-03-21   965.27  1012.516667         NaN  216.690775
          2016-03-22   630.77   836.760000         NaN  217.842052
          2016-03-23   702.79   766.276667  851.125000  161.669232
          2016-03-24   728.15   687.236667  830.141667  145.007117

The notation `"mean": [[1, 3]]` (captured in the column `"y_mean_1_3"`) is read as:

summarization function `"mean": [[1, 3]]` is applied to:

* window of length 3
* start (inclusive) is lagged by one period

Visualization:

For z = target time stamp:\
`window = [1, 3]`, means a `lag` of 1 and `window_length` of 3, selecting the three last days (exclusive z).

Summarization is done across windows like this:

| x x x x x x x x * * * z x |
|---------------------------|

By default, `"WindowSummarizer"` uses pandas rolling window functions to allow for a speedy generation of features. 
* "sum",
* "mean",
* "median",
* "std",
* "var",
* "kurt",
* "min",
* "max",
* "corr",
* "cov",
* "skew",
* "sem"

typically very fast since optimized for rolling, grouped operations

In the M5 competition, arguably the most relevant features were:

* **mean** calculations to capture level shifts, e.g. last week sales, sales of the week prior to the last month etc.
* **standard deviation** to capture increases / decreases in volatility in sales, and how it impacts future sales
* rolling **skewness** / **kurtosis** calculations, to capture changes in store sales tendencies.
* various different calculations to capture periods of zero sales (e.g. out of stock scenarios)

First three are available via native pandas functions.\
`WindowSummarizer` can also be provided with arbitrary summarizer functions.

Example: function `count_gt130` to count how many observations lie above the threshold of 130 within a window of length 3, lagged by 2 periods.

In [26]:
import numpy as np


def count_gt130(x):
    """Count how many observations lie above threshold 130."""
    return np.sum((x > 700)[::-1])


kwargs = {
    "lag_feature": {
        "lag": [1],
        count_gt130: [[2, 3]],
        "std": [[1, 4]],
    }
}

transformer = WindowSummarizer(**kwargs)
y_transformed = transformer.fit_transform(y_train)

y_transformed.head(10)

                      y_lag_1  y_count_gt130_2_3   y_std_1_4
instances timepoints
1         2016-03-15      NaN                NaN         NaN
          2016-03-16   756.67                NaN         NaN
          2016-03-17   679.13                NaN         NaN
          2016-03-18   633.40                NaN         NaN
          2016-03-19  1158.04                1.0  239.617572
          2016-03-20   914.24                1.0  241.571143
          2016-03-21   965.27                2.0  216.690775
          2016-03-22   630.77                3.0  217.842052
          2016-03-23   702.79                2.0  161.669232
          2016-03-24   728.15                2.0  145.007117

Above applies `"WindowSummarizer"` to the forecasting targey `y`.

To apply `"WindowSummarizer"` to columns in `X`, use `"WindowSummarizer"` within a `"ForecastingPipeline"` and specify `"target_cols"`.

In the M5 competition, lagging of exogeneous features was especially useful for lags around holiday dummies (often sales are affected for a few days before and after major holidays) as well as changes in item prices (discounts as well as persistent price changes)

In [27]:
from sktime.datasets import load_longley
from sktime.forecasting.naive import NaiveForecaster

y_ll, X_ll = load_longley()
y_train_ll, y_test_ll, X_train_ll, X_test_ll = temporal_train_test_split(y_ll, X_ll)
fh = ForecastingHorizon(X_test_ll.index, is_relative=False)
# Example transforming only X
pipe = ForecastingPipeline(
    steps=[
        ("a", WindowSummarizer(n_jobs=1, target_cols=["POP", "GNPDEFL"])),
        ("b", WindowSummarizer(n_jobs=1, target_cols=["GNP"], **kwargs)),
        ("forecaster", NaiveForecaster(strategy="drift")),
    ]
)
pipe_return = pipe.fit(y_train_ll, X_train_ll)
y_pred1 = pipe_return.predict(fh=fh, X=X_test_ll)

y_pred1

1959    67075.727273
1960    67638.454545
1961    68201.181818
1962    68763.909091
Freq: A-DEC, dtype: float64

For efficiency, relevant features are computed in a parallel way.\
For maximum parallelization, pass `WindowSummarizer` as a single transformer within `make_reduction`. 

In this case, `window_length` is inferred from the `WindowSummarizer` and need not be passed to `make_reduction`.

In [28]:
forecaster = make_reduction(
    regressor,
    transformers=[WindowSummarizer(**kwargs, n_jobs=1)],
    window_length=None,
    strategy="recursive",
    pooling="global",
)

Concepts relating to calendar seasonalities need to be provided by means of feature engineering to most models. Examples:

* day of the week effects historically observed for stock prices (prices on Fridays used to differ from Monday prices).
* used car prices being higher in spring than in summer
* spendings at the beginning of the month differing from end of month due to salary effects.

Calendar seasonalities can be modeled by means of dummy variables or fourier terms. As a rule of thumb, use dummy variables for discontinuous effects and fourier/period/seasonality terms when you believe there is a certain degree of smoothness in the seasonality.

`sktime` supports calendar dummy features via the `DateTimeFeatures` transformer. Manually specify the desired seasonality, or provide base frequency of the time series (daily, weekly etc.) and the desired complexity (few vs many features), `DateTimeFeatures` can infer sensible seasonality.

In [29]:
transformer = DateTimeFeatures(ts_freq="D")
X_hat = transformer.fit_transform(X_train)

new_cols = [i for i in X_hat if i not in X_train.columns]
X_hat[new_cols]

                      year  month  weekday
instances timepoints
1         2016-03-15  2016      3        1
          2016-03-16  2016      3        2
          2016-03-17  2016      3        3
          2016-03-18  2016      3        4
          2016-03-19  2016      3        5
          2016-03-20  2016      3        6
          2016-03-21  2016      3        0
          2016-03-22  2016      3        1
          2016-03-23  2016      3        2
          2016-03-24  2016      3        3
          2016-03-25  2016      3        4
          2016-03-26  2016      3        5
          2016-03-27  2016      3        6
          2016-03-28  2016      3        0
          2016-03-29  2016      3        1
          2016-03-30  2016      3        2
          2016-03-31  2016      3        3
          2016-04-01  2016      4        4
          2016-04-02  2016      4        5
          2016-04-03  2016      4        6
          2016-04-04  2016      4        0
          2016-04-05  2016      4        1
          2016-04-06  2016      4        2
          2016-04-07  2016      4        3
          2016-04-08  2016      4        4
          2016-04-09  2016      4        5
          2016-04-10  2016      4        6
          2016-04-11  2016      4        0
          2016-04-12  2016      4        1
          2016-04-13  2016      4        2
2         2016-03-15  2016      3        1
          2016-03-16  2016      3        2
          2016-03-17  2016      3        3
          2016-03-18  2016      3        4
          2016-03-19  2016      3        5
          2016-03-20  2016      3        6
          2016-03-21  2016      3        0
          2016-03-22  2016      3        1
          2016-03-23  2016      3        2
          2016-03-24  2016      3        3
          2016-03-25  2016      3        4
          2016-03-26  2016      3        5
          2016-03-27  2016      3        6
          2016-03-28  2016      3        0
          2016-03-29  2016      3        1
          2016-03-30  2016      3        2
          2016-03-31  2016      3        3
          2016-04-01  2016      4        4
          2016-04-02  2016      4        5
          2016-04-03  2016      4        6
          2016-04-04  2016      4        0
          2016-04-05  2016      4        1
          2016-04-06  2016      4        2
          2016-04-07  2016      4        3
          2016-04-08  2016      4        4
          2016-04-09  2016      4        5
          2016-04-10  2016      4        6
          2016-04-11  2016      4        0
          2016-04-12  2016      4        1
          2016-04-13  2016      4        2

DateTimeFeatures supports the following frequencies:
* Y - year
* Q - quarter
* M - month
* W - week
* D - day
* H - hour
* T - minute
* S - second
* L - millisecond

You can specify the manual generation of dummy features with the notation e.g. "day_of_month", "day_of_week", "week_of_quarter".

In [30]:
transformer = DateTimeFeatures(manual_selection=["week_of_month", "day_of_quarter"])
X_hat = transformer.fit_transform(X_train)

new_cols = [i for i in X_hat if i not in X_train.columns]
X_hat[new_cols]

                      day_of_quarter  week_of_month
instances timepoints
1         2016-03-15              75              3
          2016-03-16              76              3
          2016-03-17              77              3
          2016-03-18              78              3
          2016-03-19              79              3
          2016-03-20              80              3
          2016-03-21              81              3
          2016-03-22              82              4
          2016-03-23              83              4
          2016-03-24              84              4
          2016-03-25              85              4
          2016-03-26              86              4
          2016-03-27              87              4
          2016-03-28              88              4
          2016-03-29              89              5
          2016-03-30              90              5
          2016-03-31              91              5
          2016-04-01               1              1
          2016-04-02               2              1
          2016-04-03               3              1
          2016-04-04               4              1
          2016-04-05               5              1
          2016-04-06               6              1
          2016-04-07               7              1
          2016-04-08               8              2
          2016-04-09               9              2
          2016-04-10              10              2
          2016-04-11              11              2
          2016-04-12              12              2
          2016-04-13              13              2
2         2016-03-15              75              3
          2016-03-16              76              3
          2016-03-17              77              3
          2016-03-18              78              3
          2016-03-19              79              3
          2016-03-20              80              3
          2016-03-21              81              3
          2016-03-22              82              4
          2016-03-23              83              4
          2016-03-24              84              4
          2016-03-25              85              4
          2016-03-26              86              4
          2016-03-27              87              4
          2016-03-28              88              4
          2016-03-29              89              5
          2016-03-30              90              5
          2016-03-31              91              5
          2016-04-01               1              1
          2016-04-02               2              1
          2016-04-03               3              1
          2016-04-04               4              1
          2016-04-05               5              1
          2016-04-06               6              1
          2016-04-07               7              1
          2016-04-08               8              2
          2016-04-09               9              2
          2016-04-10              10              2
          2016-04-11              11              2
          2016-04-12              12              2
          2016-04-13              13              2

#### Putting it all together

Using the `"WindowSummarizer"`, `"DateTimeFeatures"` and the `"make_reduction"` function we can now set up a working example of a an end to end Global forecasting pipeline based on a sample of the M5 competition data:

In [31]:
pipe = ForecastingPipeline(
    steps=[
        (
            "event_dynamics",
            WindowSummarizer(
                n_jobs=-1, **kwargs, target_cols=["event_type_1", "event_type_2"]
            ),
        ),
        ("snap_dynamics", WindowSummarizer(n_jobs=-1, target_cols=["snap"])),
        ("daily_season", DateTimeFeatures(ts_freq="D")),
        ("forecaster", forecaster),
    ]
)

pipe_return = pipe.fit(y_train, X_train)
y_pred1 = pipe_return.predict(fh=1, X=X_test)

y_pred1

                            y
instances timepoints
1         2016-03-15   756.67
2         2016-03-15  1901.15

---
## Building your own hierarchical forecaster

Getting started:

* follow the ["implementing estimator" developer guide](https://www.sktime.net/en/stable/developer_guide/add_estimators.html)
* use the advanced [forecasting extension template](https://github.com/sktime/sktime/blob/main/extension_templates/forecasting.py)

Extension template = python "fill-in" template with to-do blocks that allow you to implement your own, sktime-compatible forecasting algorithm.

Check estimators using `check_estimator`

For hierarchical forecasting:

* ensure to pick supported mtypes for panel and hierarchical data
* recommended: `y_inner_mtype = ["pd.DataFrame", "pd-multiindex", "pd_multiindex_hier"]`, same for `X_inner_mtype`
    * this ensures the inputs `y`, `X` seen in `_fit`, `_predict` are `pd.DataFrame`, with 1, 2, 3 or more row levels
* you can implement vectorization over rows if efficient implementation is available
    * but: automated vectorization already loops over row index sets, don't implement that if that's what "hierarchical" is
    * to ensure automated vectorization, do *not* include Hierarchical or Panel mtypes in `y_inner_mtype`, `X_inner_mtype`
* think carefully whether your estimator is a forecaster, or can be decomposed in a transformer
    * "do X and then apply forecaster already in sktime" is a strong hint that you actually want to implement a transformer

---

### Credits

notebook creation: danbartl, fkiraly

hierarchical forecasting framework: ciaran-g, fkiraly\
reduction compatibility with hierarchical forecasting: danbartl\
window summarizer, reduction with transform-from-y: danbartl\
aggregation and reconciliation: ciaran-g
global forecast: Xinyu Wu